#ifndef ERROR_CODE_H
#define ERROR_CODE_H

typedef enum {
  ERROR_CODE_OK,
  ERROR_CODE_TARGET_INIT_FAILED,
  ERROR_CODE_TIMERS_CALLBACKS_FULL,

  ERROR_CODE_NETWORK_SOCKET_FAIL = 100,
  ERROR_CODE_NETWORK_BIND_FAIL,
  ERROR_CODE_NETWORK_LISTEN_FAIL,
  ERROR_CODE_NETWORK_START_FAILED,
  ERROR_CODE_NETWORK_SEND_FAILED,
  ERROR_CODE_NETWORK_RECEIVE_FAILED,

  ERROR_CODE_FILES_NOT_FOUND = 200,
  ERROR_CODE_FILES_NOT_OPEN,
  ERROR_CODE_FILES_READ_FAIL,
  ERROR_CODE_FILES_SIZE_FAIL,

  ERROR_CODE_PROGRAMS_NONE = 300,
  ERROR_CODE_PROGRAMS_NOT_FOUND,
  ERROR_CODE_PROGRAMS_READ_FAIL,

  ERROR_CODE_HTTPD_TOKINIZE_FAILED = 400,
  ERROR_CODE_HTTPD_NO_MORE_HANDLERS,
  ERROR_CODE_HTTPD_NO_FILE,
  ERROR_CODE_HTTPD_NO_HANDLER,
  ERROR_CODE_HTTPD_BAD_HANDLER,
  ERROR_CODE_HTTPD_TOO_MANY_METHODS,

  ERROR_CODE_PROGRAM_JSON_INVALID = 500,
  ERROR_CODE_PROGRAM_JSON_TAG_NOT_FOUND,
  ERROR_CODE_PROGRAM_JSON_ITERATOR_FAILED,
  ERROR_CODE_PROGRAM_INVALID_SERIE,
  ERROR_CODE_PROGRAM_NOT_IDLE,
  ERROR_CODE_PROGRAM_LISTENERS_FULL,

  ERROR_CODE_AUDIO_INIT_FAILED = 600,
  ERROR_CODE_AUDIO_PLAY_FAILED,
  ERROR_CODE_AUDIO_NONE,
  ERROR_CODE_AUDIO_NOT_FOUND,

  ERROR_CODE_WAVE_INVALID_FORMAT = 700,

} error_code_t;

#endif // ERROR_CODE_H
